### PR TITLE
closes #20 wrong transport syntax - allow client to set

### LINKED ISSUE #20: Broken DICOM from Orthanc example server

### PR DESCRIPTION
**Pull request by nickhingston**

### CODE REVIEW

File: src/parser/image.ts [hunk 1]
```diff
@@ -902,6 +902,13 @@ class DCMImage implements IImageInfo {
 		return this.getTagValueIndexed(TagIds.TransferSyntax) as TransferSyntax;
 	}
 
+	/**
+	 * Sets the tranfer syntax - so we can override it
+	 */
+	set transferSyntax(syntax: TransferSyntax) {
+		this.getTag(TagIds.TransferSyntax).convertedValue = syntax;
```
Comment (vespasianvs) [inline src/parser/image.ts:909]: Does this need validating? What happens if I call transferSyntax = "JunkSyntax" from a JS file (not TS, so no type validation)?

**Review by vespasianvs — CHANGES_REQUESTED** [review]
